### ISSUE TITLE
Data export

### ISSUE THREAD

**Issue by h-m-m** [rubyforgood/working_landscapes#2]
All data entered in to the system needs an export functionality. CSV is fine to start with.
- [x] The most basic export is: given a site and protocol, export all observations and their sample and entry info. This should look like classic join, where each row corresponds to one entry. 
- [x] The columns for each entry should contain the human-readable columns for the property, site, subsite, sample, and entry.
- [ ] After that's working, break up the hstore columns so that each key has its own column populated with the values for that sample and entry

**Comment by juliancheal** [comment]
Happy to work on this one.

**Comment by h-m-m** [comment]
@juliancheal I've updated the Github wiki with some basics about the project. Hopefully that's enough to help you get started on this. If not, please let me know.

**Comment by h-m-m** [comment]
This is mostly done. Only thing remaining is to double-check and make sure we haven't missed anything important.

**Comment by h-m-m** [comment]
Closing this ticket in favor of breaking it down in to new issues.
