### ISSUE TITLE
Can we remove the spring gem?

### ISSUE THREAD

**Issue by danielpclark** [rubyforgood/working_landscapes#23]
Unless this is helpful to anyone I'd like this gem removed.

**Comment by h-m-m** [comment]
@danielpclark Is it interfering with your workflow?

**Comment by danielpclark** [comment]
I have a slow netbook.  It slows down startup for me which is the opposite of its design.  It's not painful, I just feel it's not fulfilling any purpose for us.

I've always removed it from my Rails projects and don't see and side effects by doing that.

**Comment by cflipse** [comment]
generally concur with removing, but not passionately at the moment

**Comment by h-m-m** [comment]
Works for me. Will merge in as PR #29
