### ISSUE TITLE
Github Wiki Link broken

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/working_landscapes#75]
On the Readme, under the section "Application Structure" the link for the Github wiki is broken.

**Comment by h-m-m** [comment]
I was relying on relative url behavior that looks like it's inconsistent between browsers. I think I fixed it. Could you check and make sure it's working in your browser?

**Comment by AliSchlereth** [comment]
@h-m-m I'm seeing the same behavior as @pollygee. When I visit the README, and I click "GitHub wiki" it takes me to a 404.

**Comment by h-m-m** [comment]
Oh, I see.  thought Polly was talking about a link within the wiki to elsewhere in the wiki that was also broken, not a link in the committed README file itself.
