### ISSUE TITLE
Add more navigation links

### ISSUE THREAD

**Issue by h-m-m** [rubyforgood/working_landscapes#80]
This is a follow-up to #67 

There is no link to the page for creating a new protocol. Let's add that to the Manage Protocols page. Below the "Add Observations" link on that page, add a link that says "Add a New Protocol"

It would help if those two "Add" links are also clearly distinct from the other links on that survey_protocols page. Putting the list of protocols (and the links to edit them) in an unordered list will be good enough to accomplish this.

**Comment by AliSchlereth** [comment]
Hi @h-m-m ,
  I've put in a PR with the above described Navigation Updates. Please let me know if you'd like any further adjustments.

**Comment by h-m-m** [comment]
Great. I'm going to push this up to Heroku now and ask our contacts at Virginia Working Landscapes to have a look and let me know their thoughts. I'll open new issues based on their feedback, hopefully within a week.
